# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'xmlyFM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  use_frameworks!
  # 忽略引入库的所有警告
  inhibit_all_warnings!
  # Pods for xmlyFM
  pod 'SnapKit'
  pod 'Kingfisher'
  #tabbar样式
  pod 'ESTabBarController-swift', '~> 2.6.2'
  #banner滚动图片
  pod 'FSPagerView'
  pod 'Moya'
  pod 'HandyJSON', '~> 4.2.0'
  pod 'SwiftyJSON'
  # 分页
  pod 'DNSPageView', '~> 1.0.1'
  #跑马灯
  pod 'JXMarqueeView'
  #滚动页
  pod 'LTScrollView'
  pod 'MJRefresh'
  #pod 'SkeletonView'
  #消息提示
  pod 'SwiftMessages', '~> 6.0.1'
  #pod 'YYKit'
  pod 'SVProgressHUD'
  #播放网络音频
  pod 'StreamingKit'


  target 'xmlyFMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xmlyFMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
